// <auto-generated />
using System;
using FinancialIntelligence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialIntelligence.Infrastructure.Migrations
{
    [DbContext(typeof(FinancialIntelligenceDbContext))]
    [Migration("20260929153702_AddFinancialFacts")]
    partial class AddFinancialFacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialIntelligence.Domain.Companies.Company", b =>
                {
                    b.Property<int>("CvmCode")
                        .HasColumnType("integer")
                        .HasColumnName("cvm_code");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("registration_status");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.Property<string>("Ticker")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ticker");

                    b.HasKey("CvmCode")
                        .HasName("pk_companies");

                    b.HasIndex("Cnpj")
                        .HasDatabaseName("ix_companies_cnpj");

                    b.HasIndex("Ticker")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_ticker");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("FinancialIntelligence.Domain.FinancialData.FinancialFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_code");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("basis");

                    b.Property<int>("CvmCode")
                        .HasColumnType("integer")
                        .HasColumnName("cvm_code");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_file");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_financial_facts");

                    b.HasIndex("CvmCode", "AccountCode", "Basis", "PeriodStart", "PeriodEnd", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_financial_facts_value_identity");

                    b.ToTable("financial_facts", (string)null);
                });

            modelBuilder.Entity("FinancialIntelligence.Domain.FinancialData.FinancialFact", b =>
                {
                    b.HasOne("FinancialIntelligence.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CvmCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_facts_companies_cvm_code");
                });
#pragma warning restore 612, 618
        }
    }
}
